title: productionSeriesSubtitle
description: >-
  The title of a part or section of a production series.  Parts or sections refer to segments,
  such as individual episodes, in a production series. The word "series" is used in a non-archival
  sense. It specifically refers to motion pictures, sound recordings, or videotapes produced as a
  series, such as a television series or movie serials.
type: string
example: America's Civil Rights Years (1954-1965)